=== RaulPerezAguilar/LENGUAJES/UD2/ACTIVIDAD/validacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="registro_logistica">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paquete" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="remitente" type="xs:string" />

                            <xs:element name="peso_kg">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:minInclusive value="0.1" />
                                        <xs:maxInclusive value="50.0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="entregado" type="xs:boolean" />
                            <xs:element name="fecha_admision" type="xs:date" />

                            <xs:element name="coordenadas_gps">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern
                                            value="-?[0-9]{1,2}\.[0-9]+,-?[0-9]{1,3}\.[0-9]+" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="historial">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="evento" minOccurs="1"
                                            maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="hora" type="xs:dateTime"
                                                            use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>

                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[A-Z]{3}-[0-9]{3}" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="urgencia" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="Express" />
                                    <xs:enumeration value="Standard" />
                                    <xs:enumeration value="BajoCoste" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== RaulPerezAguilar/LENGUAJES/UD2/ACTIVIDAD/envios.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro_logistica
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="validacion.xsd">

    <paquete id="SEV-001" urgencia="Express">
        <remitente>Empresa Andaluza SL</remitente>
        <peso_kg>2.5</peso_kg>
        <entregado>true</entregado>
        <fecha_admision>2025-01-10</fecha_admision>
        <coordenadas_gps>37.3891,-5.9845</coordenadas_gps>
        <historial>
            <evento hora="2025-01-10T08:00:00">Salida de almacén</evento>
            <evento hora="2025-01-10T10:30:00">En reparto</evento>
            <evento hora="2025-01-10T13:15:00">Entregado</evento>
        </historial>
    </paquete>

    <paquete id="MAD-245" urgencia="Standard">
        <remitente>Logística Central</remitente>
        <peso_kg>15.0</peso_kg>
        <entregado>false</entregado>
        <fecha_admision>2025-01-12</fecha_admision>
        <coordenadas_gps>40.4168,-3.7038</coordenadas_gps>
        <historial>
            <evento hora="2025-01-12T09:00:00">Salida de almacén</evento>
            <evento hora="2025-01-13T07:45:00">En tránsito</evento>
        </historial>
    </paquete>

    <paquete id="BCN-999" urgencia="BajoCoste">
        <remitente>Juan Pérez</remitente>
        <peso_kg>0.8</peso_kg>
        <entregado>true</entregado>
        <fecha_admision>2025-01-15</fecha_admision>
        <coordenadas_gps>41.3874,2.1686</coordenadas_gps>
        <historial>
            <evento hora="2025-01-15T06:30:00">Salida de almacén</evento>
            <evento hora="2025-01-16T12:00:00">Entregado</evento>
        </historial>
    </paquete>

</registro_logistica>

=== RaulPerezAguilar/LENGUAJES/UD2/envios.xml
<?xml version="1.0" encoding="UTF-8"?>
<registro_logistica
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="validacion.xsd">

    <paquete id="SEV-001" urgencia="Express">
        <remitente>Empresa Andaluza SL</remitente>
        <peso_kg>2.5</peso_kg>
        <entregado>true</entregado>
        <fecha_admision>2025-01-10</fecha_admision>
    </paquete>

    <paquete id="MAD-245" urgencia="Standard">
        <remitente>Logística Central</remitente>
        <peso_kg>15.0</peso_kg>
        <entregado>false</entregado>
        <fecha_admision>2025-01-12</fecha_admision>
    </paquete>

    <paquete id="BCN-999" urgencia="BajoCoste">
        <remitente>Juan Pérez</remitente>
        <peso_kg>0.8</peso_kg>
        <entregado>true</entregado>
        <fecha_admision>2025-01-15</fecha_admision>
    </paquete>

</registro_logistica>
